function getSqlConn_mysql {
    local user=$1
    local passwd=$2
    local ipAddr=$3
    local dbName=$4
    local port=$5
    if [ ! "x${port}" = "x" ];then
        local port=":${port}"
    fi
    echo "mysql://${user}:${passwd}@${ipAddr}${port}/${dbName}?charset=utf8"
}

function initDb_mysql {
    echo "
DROP DATABASE IF EXISTS keystone;
CREATE DATABASE IF NOT EXISTS keystone;
GRANT ALL PRIVILEGES ON ${REMOTE_DATABASE_USER}.* TO 'keystone'@'%' IDENTIFIED BY '${REMOTE_DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON ${REMOTE_DATABASE_USER}.* TO 'keystone'@'localhost' IDENTIFIED BY '${REMOTE_DATABASE_PASSWORD}';

DROP DATABASE IF EXISTS glance;
CREATE DATABASE IF NOT EXISTS glance;
GRANT ALL PRIVILEGES ON ${REMOTE_DATABASE_USER}.* TO 'glance'@'%' IDENTIFIED BY '${REMOTE_DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON ${REMOTE_DATABASE_USER}.* TO 'glance'@'localhost' IDENTIFIED BY '${REMOTE_DATABASE_PASSWORD}';

DROP DATABASE IF EXISTS nova;
CREATE DATABASE IF NOT EXISTS nova;
GRANT ALL PRIVILEGES ON ${REMOTE_DATABASE_USER}.* TO 'nova'@'%' IDENTIFIED BY '${REMOTE_DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON ${REMOTE_DATABASE_USER}.* TO 'nova'@'localhost' IDENTIFIED BY '${REMOTE_DATABASE_PASSWORD}';

DROP DATABASE IF EXISTS cinder;
CREATE DATABASE IF NOT EXISTS cinder;
GRANT ALL PRIVILEGES ON ${REMOTE_DATABASE_USER}.* TO 'cinder'@'%' IDENTIFIED BY '${REMOTE_DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON ${REMOTE_DATABASE_USER}.* TO 'cinder'@'localhost' IDENTIFIED BY '${REMOTE_DATABASE_PASSWORD}';

DROP DATABASE IF EXISTS quantum;
CREATE DATABASE IF NOT EXISTS quantum;
GRANT ALL PRIVILEGES ON ${REMOTE_DATABASE_USER}.* TO 'quantum'@'%' IDENTIFIED BY '${REMOTE_DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON ${REMOTE_DATABASE_USER}.* TO 'quantum'@'localhost' IDENTIFIED BY '${REMOTE_DATABASE_PASSWORD}';
" > /tmp/init.sql

    mysql -u root -p${REMOTE_DATABASE_PASSWORD} < /tmp/init.sql
}
